//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O mě.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žánr.
        /// </summary>
        public static string BCName {
            get {
                return ResourceManager.GetString("BCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chytrákův blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knihy.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napište mi.
        /// </summary>
        public static string ContactForm {
            get {
                return ResourceManager.GetString("ContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Životopis.
        /// </summary>
        public static string CV {
            get {
                return ResourceManager.GetString("CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Životopis v pdf.
        /// </summary>
        public static string CVText {
            get {
                return ResourceManager.GetString("CVText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to česky.
        /// </summary>
        public static string Czech {
            get {
                return ResourceManager.GetString("Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vzdělání.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to david.kovac@uhk.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anglicky.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praxe.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úvod.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrázek.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název obrázku.
        /// </summary>
        public static string ImageName {
            get {
                return ResourceManager.GetString("ImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zájmy.
        /// </summary>
        public static string Intersets {
            get {
                return ResourceManager.GetString("Intersets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znalosti a dovednosti.
        /// </summary>
        public static string Knowledge {
            get {
                return ResourceManager.GetString("Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazyky.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.povolená délka názvu kategorie je 10 znaků!.
        /// </summary>
        public static string LenghtACT {
            get {
                return ResourceManager.GetString("LenghtACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. délka názvu je 100 znaků!.
        /// </summary>
        public static string LenghtAT {
            get {
                return ResourceManager.GetString("LenghtAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. délka popisu článku je 500 znaků!.
        /// </summary>
        public static string LenghtDA {
            get {
                return ResourceManager.GetString("LenghtDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. délka popisu kategorie je 50 znaků!.
        /// </summary>
        public static string LenghtDAC {
            get {
                return ResourceManager.GetString("LenghtDAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. délka popisu knihy je 500 znaků.
        /// </summary>
        public static string LenghtDB {
            get {
                return ResourceManager.GetString("LenghtDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. délka popisu žánru je 10 znaků.
        /// </summary>
        public static string LenghtDBCMax {
            get {
                return ResourceManager.GetString("LenghtDBCMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. délka popisu role je 10 znaků!.
        /// </summary>
        public static string LenghtDR {
            get {
                return ResourceManager.GetString("LenghtDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. délka keywords je 100 znaků.
        /// </summary>
        public static string LenghtK {
            get {
                return ResourceManager.GetString("LenghtK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. délka metadat je 200 znaků!.
        /// </summary>
        public static string LenghtM {
            get {
                return ResourceManager.GetString("LenghtM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. délka názvu žánru je 50 znaků.
        /// </summary>
        public static string LenghtNBCMax {
            get {
                return ResourceManager.GetString("LenghtNBCMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délka hesla musí mít min 5 znaků!.
        /// </summary>
        public static string LenghtPassMin {
            get {
                return ResourceManager.GetString("LenghtPassMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. délka popisu role je 10 znaků.
        /// </summary>
        public static string LenghtRDMax {
            get {
                return ResourceManager.GetString("LenghtRDMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. délka názvu role je 10 znaků.
        /// </summary>
        public static string LenghtRNMax {
            get {
                return ResourceManager.GetString("LenghtRNMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. délka názvu je 100 znaků.
        /// </summary>
        public static string LenghtTB {
            get {
                return ResourceManager.GetString("LenghtTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string Metadata {
            get {
                return ResourceManager.GetString("Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pokračovat.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David.
        /// </summary>
        public static string MyName {
            get {
                return ResourceManager.GetString("MyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kováč.
        /// </summary>
        public static string MySurname {
            get {
                return ResourceManager.GetString("MySurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přezdívka.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015.
        /// </summary>
        public static string OriginYear {
            get {
                return ResourceManager.GetString("OriginYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prostřední jméno.
        /// </summary>
        public static string PersonMiddleName {
            get {
                return ResourceManager.GetString("PersonMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string PersonName {
            get {
                return ResourceManager.GetString("PersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        public static string PersonSurname {
            get {
                return ResourceManager.GetString("PersonSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string PosteDate {
            get {
                return ResourceManager.GetString("PosteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název kategorie je povinný!.
        /// </summary>
        public static string RequiredACT {
            get {
                return ResourceManager.GetString("RequiredACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadpis je povinný!.
        /// </summary>
        public static string RequiredAT {
            get {
                return ResourceManager.GetString("RequiredAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text článku je povinný!.
        /// </summary>
        public static string RequiredAText {
            get {
                return ResourceManager.GetString("RequiredAText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor je povinný!.
        /// </summary>
        public static string RequiredAuthor {
            get {
                return ResourceManager.GetString("RequiredAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žánr je povinný!.
        /// </summary>
        public static string RequiredCB {
            get {
                return ResourceManager.GetString("RequiredCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis článku je povinný!.
        /// </summary>
        public static string RequiredDA {
            get {
                return ResourceManager.GetString("RequiredDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis kategorie je povinný!.
        /// </summary>
        public static string RequiredDAC {
            get {
                return ResourceManager.GetString("RequiredDAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis knihy je povinný!.
        /// </summary>
        public static string RequiredDB {
            get {
                return ResourceManager.GetString("RequiredDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis žánru je poviný!.
        /// </summary>
        public static string RequiredDBC {
            get {
                return ResourceManager.GetString("RequiredDBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis role je povinný!.
        /// </summary>
        public static string RequiredDR {
            get {
                return ResourceManager.GetString("RequiredDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je povinný!.
        /// </summary>
        public static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords je povinný!.
        /// </summary>
        public static string RequiredK {
            get {
                return ResourceManager.GetString("RequiredK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata jsou povinná!.
        /// </summary>
        public static string RequiredM {
            get {
                return ResourceManager.GetString("RequiredM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název žánru je povinný!.
        /// </summary>
        public static string RequiredNBC {
            get {
                return ResourceManager.GetString("RequiredNBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přezdívka je povinná!.
        /// </summary>
        public static string RequiredNickaname {
            get {
                return ResourceManager.GetString("RequiredNickaname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo je povinné!.
        /// </summary>
        public static string RequiredPass {
            get {
                return ResourceManager.GetString("RequiredPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno je povinné!.
        /// </summary>
        public static string RequiredPN {
            get {
                return ResourceManager.GetString("RequiredPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení je povinné!.
        /// </summary>
        public static string RequiredPS {
            get {
                return ResourceManager.GetString("RequiredPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název role je povinný!.
        /// </summary>
        public static string RequiredRN {
            get {
                return ResourceManager.GetString("RequiredRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název knihy je povinný!.
        /// </summary>
        public static string RequiredTB {
            get {
                return ResourceManager.GetString("RequiredTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název role.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krátce o mě.
        /// </summary>
        public static string ShortBio {
            get {
                return ResourceManager.GetString("ShortBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Česká Republika.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextA {
            get {
                return ResourceManager.GetString("TextA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadpis.
        /// </summary>
        public static string TitleA {
            get {
                return ResourceManager.GetString("TitleA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string TitleAC {
            get {
                return ResourceManager.GetString("TitleAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název knihy.
        /// </summary>
        public static string TitleB {
            get {
                return ResourceManager.GetString("TitleB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svoboda nad Úpou.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vítejte na mých osobních stránkách!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyto stránky jsou odrazem mých školních či volnočasových aktivit, jsou tedy určeny (nejen) těm návštěvníkům,
        ///            kteří se věnují podobným aktivitám a shánějí v jejich rámci nějaké rozšiřující informace, ať už formou článku nebo vhodného odkazu.
        ///            Pokud sdílíte mé nadšení z matematiky, informační bezpečnosti a jim příbuzných témat, pak jste .
        /// </summary>
        public static string Welcometext {
            get {
                return ResourceManager.GetString("Welcometext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatný formát emailu!!!.
        /// </summary>
        public static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
    }
}
